destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/gtt-pdf"
port: 4010
output: pdf
product: gtt
print_title: GDAX Trading Toolkit - Users' Guide
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
